# Generated by Django 4.0.4 on 2022-12-31 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(verbose_name='user_id')),
                ('first_name', models.CharField(max_length=256, verbose_name='name')),
                ('last_name', models.CharField(max_length=256, verbose_name='name')),
                ('username', models.CharField(max_length=256, verbose_name='username')),
                ('avatarka', models.ImageField(blank=True, null=True, upload_to='user_avatars/', verbose_name='avatarka')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='post_title')),
                ('image', models.ImageField(upload_to='post_images/', verbose_name='post_image')),
                ('description', models.TextField(verbose_name='post_description')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='application.user', verbose_name='owner')),
            ],
            options={
                'verbose_name': 'post',
                'verbose_name_plural': 'Posts',
            },
        ),
    ]
