# Generated by Django 4.0.4 on 2023-01-01 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_alter_user_avatarka'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatarka',
            field=models.ImageField(blank=True, default='admin.png', null=True, upload_to='user_avatars/', verbose_name='avatarka'),
        ),
    ]
